# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=10000)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
