# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=1000)),
                ('expiration', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'db_table': 'blacklist',
            },
        ),
    ]
